In [1]:
import tensorflow as tf

In [4]:
x = tf.constant(3)
x.shape

TensorShape([])

In [5]:
x1 = tf.constant([1, 2, 3])
x1.shape

TensorShape([3])

In [ ]:
x2 = tf.constant([[1, 2], [3, 4]])
x2.shape

TensorShape([2, 2])

In [ ]:
# 3d tensor (2, 3, 4)
x3 = tf.constant(
    [
        [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
    ]
)
x3.shape

TensorShape([2, 3, 4])

In [15]:
print(tf.rank(x3))

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
t1 = tf.constant([[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])
print(tf.rank(t1))

tf.Tensor(2, shape=(), dtype=int32)


In [17]:
id1 = tf.eye(3)
print(id1)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [19]:
# matrix of zeros
z1 = tf.zeros((3, 4, 5))
print(z1)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)


In [23]:
o1 = tf.ones((3, 4, 5))
print(o1)

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 4, 5), dtype=float32)


In [27]:
r1 = tf.random.uniform((3, 4, 5), minval=0, maxval=1, dtype=tf.float32)
r2 = tf.random.normal((3, 4, 5), mean=0, stddev=1, dtype=tf.float32)
print(r1)
print(r2)

tf.Tensor(
[[[5.0291061e-01 2.1524715e-01 3.3199382e-01 7.5717211e-01 2.9579806e-01]
  [8.2445145e-04 7.3835015e-01 8.2994819e-02 9.2074943e-01 1.8405676e-01]
  [9.4535458e-01 6.5458727e-01 7.3626947e-01 8.7712777e-01 3.8370764e-01]
  [4.9539673e-01 5.2715325e-01 1.2614071e-01 1.8986118e-01 9.6341848e-01]]

 [[5.9684050e-01 9.8443127e-01 4.6796179e-01 1.3292563e-01 3.6666954e-01]
  [9.9559033e-01 3.7766814e-02 2.0225191e-01 6.1761594e-01 3.3830369e-01]
  [1.7106748e-01 3.4088719e-01 2.2629571e-01 5.0055015e-01 4.8319340e-02]
  [1.0044575e-03 8.4733582e-01 8.0916381e-01 9.4478464e-01 5.1517606e-02]]

 [[2.2978747e-01 6.9476986e-01 1.6994691e-01 1.8417966e-01 7.6749504e-01]
  [8.6411071e-01 1.0880709e-02 7.4574494e-01 5.8937418e-01 2.3415875e-01]
  [5.3935385e-01 2.3803556e-01 4.8773468e-01 4.2381465e-01 2.6986933e-01]
  [6.2647843e-01 4.0898561e-02 7.6232612e-01 3.4036660e-01 7.9089057e-01]]], shape=(3, 4, 5), dtype=float32)
tf.Tensor(
[[[-2.383187   -0.8835618   0.08716791 -0.49379304 