In [1]:
import tensorflow as tf

In [3]:
original = tf.range(12)
reshaped = tf.reshape(original, [3, 4])
print("Original Tensor:")
print(original.numpy())
print("Reshaped Tensor:")
print(reshaped.numpy())

Original Tensor:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Tensor:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [4]:
model = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(10,)),
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)

c:\D-sim\pyprojs\DLRL_Internship\.venv\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# Generate Synthetic data
import numpy as np

X_train = np.random.rand(100, 10)
y_train = np.random.randint(0, 2, size=(100, 1))

In [10]:
print(X_train, y_train)

[[8.97546324e-01 4.67929510e-01 6.84186669e-01 1.18565057e-02
  9.41055731e-01 1.06908068e-01 6.57572044e-01 1.81619119e-01
  6.80986309e-01 3.49424792e-01]
 [8.21340901e-01 3.54675978e-01 3.36430936e-01 3.21129901e-01
  1.94541687e-02 6.21766597e-01 2.79841027e-01 8.87083915e-01
  1.31926670e-01 5.89344281e-01]
 [5.62196934e-01 1.87105993e-01 3.34428021e-01 4.45575026e-01
  1.22234402e-01 1.25808992e-01 4.66996130e-01 4.03239322e-02
  3.59003877e-01 3.15148289e-01]
 [2.21706390e-01 4.50675498e-01 8.35092319e-01 4.94816426e-01
  7.09561079e-01 4.81309048e-01 2.48478485e-02 3.74317096e-01
  7.54429403e-01 7.82532372e-01]
 [3.30584434e-01 5.82367495e-01 6.51333572e-01 7.09507585e-01
  1.47342863e-01 4.73223046e-01 6.37962190e-02 2.37213483e-01
  2.73523843e-01 3.04542010e-01]
 [4.33724391e-01 1.94780681e-01 6.06841349e-01 5.34490719e-01
  5.69369861e-01 2.80229574e-01 1.14669197e-01 1.21574064e-01
  6.16714011e-01 5.59406913e-01]
 [3.76559141e-01 5.22944535e-01 5.92325564e-01 6.66213417e

In [5]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [12]:
model.fit(X_train, y_train, epochs=5, batch_size=32, verbose=True)

Epoch 1/5


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8299 - loss: 0.4563
Epoch 2/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8433 - loss: 0.4521 
Epoch 3/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7843 - loss: 0.4716 
Epoch 4/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8299 - loss: 0.4585 
Epoch 5/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8164 - loss: 0.4548


In [13]:
# Evaluate the model
X_test = np.random.rand(20, 10)
y_test = np.random.randint(0, 2, size=(20, 1))
loss, accuracy = model.evaluate(X_test, y_test)
print("Test loss:", loss)
print("Test accuracy:", accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.4000 - loss: 1.0484
Test loss: 1.0484116077423096
Test accuracy: 0.4000000059604645
